### PR TITLE
wasm2c: ensure force read constraints compile for clang on mips

### LINKED ISSUE #2266: error: couldn't allocate input reg for constraint 'r' on MIPS with clang when compiling wasm2c-generated source
When compiling Firefox (which uses wasm2c) for MIPS with clang, the following error happens:
```
rlbox.wasm.c:142:1: error: couldn't allocate input reg for constraint 'r'
 DEFINE_LOAD(f32_load, f32, f32, f32)
 ^
 rlbox.wasm.c:128:14: note: expanded from macro 'DEFINE_LOAD'
     wasm_asm("" ::"r"(result));                            \
```

GCC is happy with it, but fundamentally, the asm constraint is wrong (r is for GPRs, and here the result is a floating point value).

Those constraints were added in a7d484ef3d1f64649dd9f48cb1d5434f0fda561b, and the reason given was:
> Preventing load instructions from being optimized away if their value is unused (using inline assembly with an input operand and empty code). This is necessary to f
orce an OOB trap on platforms that use mprotect and the signal handler to detect OOB.

Would using `__attribute__((used))` work instead? Or volatile?

### PR DESCRIPTION
**Pull request by shravanrn**
This is a clean slate attempt to fix #2266. To fix this i looked into how clang and gcc handle floating point constraints across a host of platforms.

Godbolt link: https://godbolt.org/z/ddeWc6ees
Results are in table below.

Given this, it seems the simplest course of action that maintains functionality as is today, but fix the mips platform is to special case this. We can separately file a bug upstream (but best case scenario is that will likely get fixed only for future clang versions, so I'm not sure we can rely on just that).

Fyi, @glandium

gcc
---

x86 - both
x86-64 - both
aarch32 - only "r"
aarch64 - only "r"
mips - only "r"
mips64 - both
riscv32 - both
riscv64 -  both
sparc - both
sparc64 - both
powerpc - both
powerpc64 - both

clang
-----
x86 - both
x64 - both
aarch32 - only "r"
aarch64 - only "r"
mips -  only "f"
mips64 - only "f"
riscv32 -  both
riscv64 -  both
powerpc64 - both

### CODE REVIEW

File: src/template/wasm2c.declarations.c [hunk 1]
```diff
@@ -47,10 +47,18 @@ static inline bool func_types_eq(const wasm_rt_func_type_t a,
 #define MEMCHECK(mem, a, t) RANGE_CHECK(mem, a, sizeof(t))
 #endif
 
-#ifdef __GNUC__
-#define wasm_asm __asm__
+#if !defined(WASM2C_DISABLED_STRICT_TRAPPING) && defined(__GNUC__)
```
Comment (keithw) [inline src/template/wasm2c.declarations.c:50]: Given that our fallback is still going to be "don't force the read" (instead of "bomb out with an error"), can we avoid adding the `WASM2C_DISABLED_STRICT_TRAPPING` macro?

**Review by keithw — COMMENTED** [review]
lgtm % comment. Thank you for doing this whole investigation!

File: src/template/wasm2c.declarations.c (hunk 1 above)
Comment (shravanrn) [reply src/template/wasm2c.declarations.c]: Fixed!

**Comment by shravanrn** [comment]
> lgtm % comment. Thank you for doing this whole investigation!

Fixed :+1:

**Review by keithw — APPROVED** [review]

File: src/template/wasm2c.declarations.c [hunk 2]
```diff
@@ -48,9 +48,17 @@ static inline bool func_types_eq(const wasm_rt_func_type_t a,
 #endif
 
 #ifdef __GNUC__
-#define wasm_asm __asm__
+#define FORCE_READ_INT(var) __asm__("" ::"r"(var));
+// Clang on Mips requires "f" constraints on floats
```
Comment (sbc100) [inline src/template/wasm2c.declarations.c:52]: Maybe add link to upstream llvm bug here, so we can perhaps remove this one day?

**Review by sbc100 — COMMENTED** [review]
I wonder if this could be accompanied by some kind CI test?  Can this be verified by simply compiling some wasm2c output with `clang --target=mips` maybe?

**Comment by shravanrn** [comment]
> I wonder if this could be accompanied by some kind CI test? Can this be verified by simply compiling some wasm2c output with `clang --target=mips` maybe?

My take is that this feels like overkill at the moment, and we can push this until/if we see other mips incompatibilities

File: src/template/wasm2c.declarations.c (hunk 2 above)
Comment (shravanrn) [reply src/template/wasm2c.declarations.c:52]: Sure, let me submit a separate PR for this

Comment (shravanrn) [reply src/template/wasm2c.declarations.c:52]: Link: https://github.com/llvm/llvm-project/issues/64241

Comment (shravanrn) [reply src/template/wasm2c.declarations.c:52]: https://github.com/WebAssembly/wabt/pull/2276

Comment (shravanrn) [reply src/template/wasm2c.declarations.c:52]: @keithw @sbc100 Looks like the bug in llvm got fixed. We may have to keep an eye if we need add an llvm version check here to keep things compatible

Comment (sbc100) [reply src/template/wasm2c.declarations.c:52]: Version check makes sense to me yes
