### PR TITLE
wasm2c: Fix handling of locals in setjmp targets

### LINKED ISSUE #2469: wasm2c: UB in exception-handling
test case:

```wasm
(module
  (tag $e0)
  (func $longjmp-bait (throw $e0))
  (func (export "setjmp-bait") (param $return-early i32) (result i32)
    (local $value i32)
    (try $try
      (do
        (br_if $try (local.get $return-early))
        (local.set $value (i32.const 1))
        (call $longjmp-bait)
      )
      (catch $e0)
    )
    (local.get $value)
  )
)

(assert_return (invoke "setjmp-bait" (i32.const 1)) (i32.const 0))
(assert_return (invoke "setjmp-bait" (i32.const 0)) (i32.const 1))
```

`(invoke "setjmp-bait" (i32.const 0))` returns 1 in debug, 0 in release.

unfortunately, fixing this might take a huge perf hit. (`volatile` locals.)

(also no, ubsan doesn't catch this yet.)

### PR DESCRIPTION
**Pull request by SoniEx2**
It is UB to read local variables after a call to `setjmp` returns, if those variables have been modified between `setjmp` and `longjmp`, unless they're marked as `volatile`. This marks them as `volatile`.

Closes #2469

### CODE REVIEW

**Comment by SoniEx2** [comment]
@sbc100

**Comment by SoniEx2** [comment]
(the tests would catch this, despite UBSAN not having a setjmp sanitizer, because CI runs tests on both debug and release builds)

File: src/c-writer.cc [hunk 1]
```diff
@@ -3109,6 +3112,11 @@ void CWriter::WriteVarsByType(const Vars& vars,
       if (typeoffunc(var) == type) {
         if (count == 0) {
           Write(type, " ");
+          if (setjmp_safe) {
+            PushFuncSection("exceptions");
+            Write("volatile ");
+            PushFuncSection();
```
Comment (sbc100) [inline src/c-writer.cc:3118]: I assume this means we only output this volatile when exceptions are enabled?

**Comment by sbc100** [comment]
> (the tests would catch this, despite UBSAN not having a setjmp sanitizer, because CI runs tests on both debug and release builds)

I'm not quite sure what you are saying here.  Do you mean the new test you are adding would fail without the fix? 

> 
> (upstreaming is proving difficult... [WebAssembly/exception-handling#332](https://github.com/WebAssembly/exception-handling/pull/332) )

File: src/c-writer.cc (hunk 1 above)
Comment (SoniEx2) [reply src/c-writer.cc:3118]: yep!

**Comment by SoniEx2** [comment]
> I'm not quite sure what you are saying here. Do you mean the new test you are adding would fail without the fix?

the test would fail without the fix, yes. like so: (note the `-O0` vs `-O3`)

```
$ cd /home/soniex2/git/github/wabt && /usr/bin/cmake -E env WASM2C_CC=/usr/bin/clang WASM2C_CFLAGS=\ -fsanitize=undefined\ -fno-sanitize-recover\ -fsanitize-blacklist=/home/soniex2/git/github/wabt/ubsan.blacklist\ -g\ -O0 /usr/bin/python3.12 /home/soniex2/git/github/wabt/test/run-tests.py --bindir /home/soniex2/git/github/wabt/out test/regress/wasm2c-ehv3-setjmp-volatile.txt 
[+1|-0|%100] (0.55s) test/regress/wasm2c-ehv3-setjmp-volatile.txt
$ cd /home/soniex2/git/github/wabt && /usr/bin/cmake -E env WASM2C_CC=/usr/bin/clang WASM2C_CFLAGS=\ -fsanitize=undefined\ -fno-sanitize-recover\ -fsanitize-blacklist=/home/soniex2/git/github/wabt/ubsan.blacklist\ -g\ -O3 /usr/bin/python3.12 /home/soniex2/git/github/wabt/test/run-tests.py --bindir /home/soniex2/git/github/wabt/out test/regress/wasm2c-ehv3-setjmp-volatile.txt 
- test/regress/wasm2c-ehv3-setjmp-volatile.txt
  expected error code 0, got 1.
  STDERR MISMATCH:
  --- expected
  +++ actual
  @@ -0,0 +1 @@
  +wasm2c-ehv3-setjmp-volatile.txt:22: assertion failed: in w2c_wasm2c__ehv3__setjmp__volatile__0__wasm_setjmp0x2Dbait(&wasm2c__ehv3__setjmp__volatile__0__wasm_instance, 0u): expected 1, got 0.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1 +1 @@
  -2/2 tests passed.
  +1/2 tests passed.


**** FAILED ******************************************************************
- test/regress/wasm2c-ehv3-setjmp-volatile.txt
    /usr/bin/python3.12 /home/soniex2/git/github/wabt/test/run-spec-wasm2c.py out/test/regress/wasm2c-ehv3-setjmp-volatile.txt --bindir=/home/soniex2/git/github/wabt/out --no-error-cmdline -o out/test/regress/wasm2c-ehv3-setjmp-volatile --enable-exceptions
```

File: src/c-writer.cc (hunk 1 above)
Comment (SoniEx2) [reply src/c-writer.cc:3118]: also, only when a try block is used.

File: src/c-writer.cc [hunk 2]
```diff
@@ -3043,15 +3044,15 @@ void CWriter::BeginFunction(const Func& func) {
...
+void CWriter::FinishFunction(size_t stack_var_section) {
   for (size_t i = 0; i < func_sections_.size(); ++i) {
     auto& [condition, stream] = func_sections_.at(i);
     std::unique_ptr<OutputBuffer> buf = stream.ReleaseOutputBuffer();
     if (condition.empty() || func_includes_.count(condition)) {
       stream_->WriteData(buf->data.data(), buf->data.size());
     }
 
-    if (i == 0) {
+    if (i == stack_var_section) {
```
Comment (sbc100) [inline src/c-writer.cc:3055]: Is the stack_var_section not always the first one in a given function?

Comment (SoniEx2) [reply src/c-writer.cc:3055]: not with these changes. we need to write `volatile` or not based on whether the function uses `try` or not, and we do that by pushing more func sections where relevant. in particular, we save the `stack_var_section` *after* writing params and locals (both of which may contain `volatile`), so we can put the stack vars in the correct place. (also, stack vars don't need `volatile` as any reused stack slots are written over after `longjmp`.)

**Review by sbc100 — APPROVED** [review]
