### PR TITLE
wasm-objdump: Print local names during disassembly

### LINKED ISSUE #1815: Local names in wasm-objdump -x
So far as I can tell, wasm-objdump doesn't use local names when printing instructions such as local.get. I wanted to check if this was so (rather than, for instance, my test file specifying the names incorrectly -- wasm2wat includes the names, so I assume this isn't the case), and whether there would be any interest in changing the behaviour to include the names of locals?

### PR DESCRIPTION
**Pull request by mwilliamson**
Fixes #1815. Some example output:

```
module.wasm:	file format wasm 0x1

Code Disassembly:

000027 func[0] <FIRST>:
 000028: 01 7f                      | local[0] type=i32
 00002a: 20 01                      | local.get 1 <local0>
 00002c: 20 00                      | local.get 0 <arg0>
 00002e: 1a                         | drop
 00002f: 1a                         | drop
 000030: 0b                         | end
```

I haven't written a test for this yet, but I wanted to check that my approach was correct, not least because it's been a while since I've written any C++.

(Unfortunately, this doesn't actually fully solve my use case since I think wasm-ld doesn't preserve local names when linking? I haven't had a chance to investigate this yet, but mention it in case anyone knows off the top of their head.)

### CODE REVIEW

File: src/binary-reader-objdump.cc [hunk 1]
```diff
@@ -500,6 +520,7 @@ class BinaryReaderObjdumpDisassemble : public BinaryReaderObjdumpBase {
   Offset last_opcode_end = 0;
   int indent_level = 0;
   Index next_reloc = 0;
+  Index function_index = 0;
```
Comment (sbc100) [inline src/binary-reader-objdump.cc:523]: How about `current_function_index` to match the members above?

**Review by sbc100 — COMMENTED** [review]
Looks good to me!

I'm actually surprised none of the test output changed.  Did you run `./test/run-tests.sh -r`?

I think the test to update would be `test/dump/extended-names.txt` BTW.

**Comment by sbc100** [comment]
Regarding wasm-ld, its very unlikely llvm to wasm-ld will be able to give useful names to locals.  At least not ones that comes from C++ or llvm-ir, because the wasm-level locals don't normally correspond any language level construct.  

The optimizers at various levels might choose to store many different things in given local over the course of the function, so even for things that fit in locals its probably not going to be useful to mapping higher level language names.

It still useful for hand-written stuff though.

File: src/binary-reader-objdump.cc (hunk 1 above)
Comment (mwilliamson) [reply src/binary-reader-objdump.cc:523]: Will do!

**Comment by mwilliamson** [comment]
> I'm actually surprised none of the test output changed. Did you run `./test/run-tests.sh -r`?

I thought I did, I could easily be mistaken though.

> I think the test to update would be `test/dump/extended-names.txt` BTW.

Great, I'll take a look. Thanks!

> Regarding wasm-ld, its very unlikely llvm to wasm-ld will be able to give useful names to locals. At least not ones that comes from C++ or llvm-ir, because the wasm-level locals don't normally correspond any language level construct.

Just to explain my use case: I've written my own toy compiler than outputs Wasm object files, which includes local names, so having llvm-ld preserve those would be helpful for debugging.

**Comment by sbc100** [comment]
> Just to explain my use case: I've written my own toy compiler than outputs Wasm object files, which includes local names, so having llvm-ld preserve those would be helpful for debugging.

Oh sure, that sounds do-able.  But yes, probably needs a wasm-ld patch to make it work.  Would be cool if we could extant that to work with `.s` format in llvm.. but that might be little more work.

**Comment by mwilliamson** [comment]
I've had a go at updating `test/dump/extended-names.txt`, so I think this is ready to go, but happy to change things as needed. Thanks for the help so far.

**Review by sbc100 — APPROVED** [review]
