### PR TITLE
Wasmdump improvments

### LINKED ISSUE #167: wasmdump cleanup
dschuff's feedback:

```
if (ctx->options->headers) {
+    printf("%-12s start=%#010" PRIzx " end=%#010" PRIzx " (size=%#010" PRIzx
```

I think the size would probably be more readable in decimal than hex.
Actually, maybe start and end, too? IIRC the JS engines report byte offsets in Decimal in error messages stacktraces.

```
+static WasmResult on_import_func(uint32_t index,
+                                 uint32_t sig_index,
```

Might be nice to print the index for imports like the rest of the things.
Or maybe even better, the combined index space (imports+defined) for globals and functions?

```
+static WasmResult on_import_global(uint32_t index,
```

Might be nice to print the type here.

```
+static WasmResult on_export(uint32_t index,
+                            WasmExternalKind kind,
+                            uint32_t item_index,
```

it's not really clear what this index means.

### PR DESCRIPTION
**Pull request by sbc100**
fixes #167

### CODE REVIEW

File: src/binary-reader-objdump.c [hunk 1]
```diff
@@ -366,16 +390,22 @@ static WasmResult on_import(uint32_t index,
...
 
 static WasmResult on_import_func(uint32_t index,
                                  uint32_t sig_index,
                                  void* user_data) {
-  print_details(user_data, " - func sig=%d\n", sig_index);
+  Context* ctx = user_data;
+  print_details(
+      user_data, " - func[%d] sig=%d " PRIstringslice "." PRIstringslice "\n",
+      ctx->function_index, sig_index,
+      WASM_PRINTF_STRING_SLICE_ARG(ctx->import_module_name),
```
Comment (binji) [inline src/binary-reader-objdump.c]: Actually, the previous way is better; we should print the module and field names for all imported types, not just functions.

File: src/binary-reader-objdump.c [hunk 2]
```diff
@@ -402,7 +432,7 @@ static WasmResult on_import_global(uint32_t index,
                                    WasmType type,
                                    WasmBool mutable_,
                                    void* user_data) {
-  print_details(user_data, " - global\n");
+  print_details(user_data, " - global mutable=%d type=%#x\n", mutable_, type);
```
Comment (binji) [inline src/binary-reader-objdump.c]: may as well use `wasm_get_type_name` here.

File: src/binary-reader-objdump.c [hunk 3]
```diff
@@ -608,7 +640,10 @@ WasmResult wasm_read_binary_objdump(struct WasmAllocator* allocator,
     reader.on_opcode_bare = on_opcode_bare;
     reader.on_opcode_uint32 = on_opcode_uint32;
     reader.on_opcode_uint32_uint32 = on_opcode_uint32_uint32;
+    reader.on_opcode_uint32_uint32 = on_opcode_uint32_uint32;
```
Comment (binji) [inline src/binary-reader-objdump.c]: dupe

File: src/binary-reader-objdump.c [hunk 4]
```diff
@@ -265,6 +270,22 @@ static WasmResult on_opcode_uint64(WasmBinaryReaderContext* ctx,
   return WASM_OK;
 }
 
+static WasmResult on_opcode_f32(WasmBinaryReaderContext* ctx,
+                                float value) {
+  Context* context = ctx->user_data;
+  size_t immediate_len = ctx->offset - context->current_opcode_offset;
+  log_opcode(context, ctx->data, immediate_len, "%f", value);
```
Comment (binji) [inline src/binary-reader-objdump.c]: maybe use %g to get nicer-looking values here (or "%.19g" to get full precision; not sure if we care about that here).

File: src/binary-reader-objdump.c [hunk 5]
```diff
@@ -35,6 +35,11 @@ typedef struct Context {
   WasmBool print_details;
   WasmBool header_printed;
   int section_found;
+
+  WasmStringSlice import_module_name;
+  WasmStringSlice import_field_name;
+
+  int function_index;
```
Comment (binji) [inline src/binary-reader-objdump.c]: OK for now, but this will be needed for other imported types too (globals, tables, memories).

**Comment by binji** [comment]
Hm, looks like OS/X doesn't print negative nan; maybe it's being canonicalized?

File: src/binary-reader-objdump.c (hunk 1 above)
Comment (sbc100) [inline src/binary-reader-objdump.c]: I updated all the import callback to format in this way

File: src/binary-reader-objdump.c (hunk 2 above)
Comment (sbc100) [inline src/binary-reader-objdump.c]: Done

File: src/binary-reader-objdump.c (hunk 3 above)
Comment (sbc100) [inline src/binary-reader-objdump.c]: Done

File: src/binary-reader-objdump.c (hunk 5 above)
Comment (sbc100) [inline src/binary-reader-objdump.c]: Ack

File: src/binary-reader-objdump.c (hunk 4 above)
Comment (sbc100) [inline src/binary-reader-objdump.c]: Done

**Comment by binji** [comment]
To handle the OS/X nan canonicalization, you can use `wasm_write_float_hex` and `wasm_write_double_hex` from literal.h instead. Or you could check for the values being nan (x != x) and special case that.

**Comment by sbc100** [comment]
Switching to %g looks like it made travis happy.. unless I'm missing something?

**Comment by sbc100** [comment]
OIC travis can be green even when OSX is not yet passing

**Comment by binji** [comment]
Yeah, it's because OSX build is slow... :-|

File: src/binary-reader-objdump.c [hunk 6]
```diff
@@ -271,18 +272,22 @@ static WasmResult on_opcode_uint64(WasmBinaryReaderContext* ctx,
...
   return WASM_OK;
 }
 
 static WasmResult on_opcode_f64(WasmBinaryReaderContext* ctx,
-                                double value) {
+                                uint64_t value) {
   Context* context = ctx->user_data;
   size_t immediate_len = ctx->offset - context->current_opcode_offset;
-  log_opcode(context, ctx->data, immediate_len, "%g", value);
+  char buffer[20];
```
Comment (binji) [inline src/binary-reader-objdump.c]: looks like this can actually be 25 characters, including null terminator. (see comment at the top of wasm_write_double_hex). I thought I added a #define for this in literal.h, but I don't see it. It's probably worth adding one, if you don't mind.

Comment (sbc100) [inline src/binary-reader-objdump.c]: Done
