### PR TITLE
Share reading/validation code between elem exprs & other const exprs

### LINKED ISSUE #2201: Is `global.get` allowed in element segments?
As far as I can tell from the webassembly spec, it should be valid to use the `global.get` instruction in an element segment.

However I am unable to use `wat2wasm` on this module

```wat
(module
  (import "m" "f" (global funcref))
  (table 0 10 funcref)
  (elem 0 (offset (i32.const 0)) funcref (global.get 0)))
```

If I try, I get this error:

```
foo.wat:4:43: error: invalid elem expression expression; must be either ref.null or ref.func.
  (elem 0 (offset (i32.const 0)) funcref (global.get 0)))
                                          ^^^^^^^^^^
```

If I use the `--no-check` flag I am able to override the check and generate a resulting `.wasm` file.

Looking at the generated file in a hexdump, it looks exactly like I would expect it to. However I am unable to get `wasm2wat` to accept this generated module, even if I use the `--no-check` flag.

Am I misreading the spec, or is this a bug in wabt?

### PR DESCRIPTION
**Pull request by keithw**
This continues the work from #1783 and reduces special handling of elem exprs, by treating them the same as other const expressions (init expressions).

Fixes #2201 (now allows global.get in an elem expr)

This is a prerequisite for updating the testsuite (spun out from #2287). It seemed cleaner to do it this way than to add a `OnElemSegmentElemExpr_GlobalGet` to all the readers and validators, given that the validation rules are the same as when global.get appears in any other const expression.

### CODE REVIEW

File: src/binary-reader-objdump.cc [hunk 1]
```diff
@@ -1711,14 +1704,22 @@ Result BinaryReaderObjdump::BeginGlobal(Index index, Type type, bool mutable_) {
...
-                                        bool as_unsigned) {
-  assert(expr.insts.size() > 0);
+                                        bool as_unsigned,
+                                        bool with_prefix) {
+  if (with_prefix) {
+    PrintDetails(" - init ");
+  }
+
+  if (expr.insts.empty()) {
+    PrintDetails("malformed\n");
```
Comment (sbc100) [inline src/binary-reader-objdump.cc:1714]: Do we do this kind of things elsewhere in this file?   How about "<MALFORMED>" to be extra clear?

**Review by sbc100 — APPROVED** [review]
Nice!  

I've long thought this would be good idea but wan't sure how to make it happen.  Thanks.

File: src/binary-reader-objdump.cc (hunk 1 above)
Comment (keithw) [reply src/binary-reader-objdump.cc:1714]: Sounds good. I went with `<EMPTY>` to be safe -- on further review I don't think an empty const expression is malformed, just invalid.
